In [2]:
import numpy as np 
import time 

In [8]:
a = np.zeros(4)
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4)
print(f"{a}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
[0.24956319 0.48558653 0.42284207 0.04639459]


In [17]:
a = np.arange(23, 78); print(f"{a}")
random_number = np.random.rand(10)*100
print(f"this is a random list {random_number}")

[23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70
 71 72 73 74 75 76 77]
this is a random list [23.64639808 98.49357037 15.58584363 44.11113009 19.51486121 24.15420751
  5.02983424  9.2310688  91.45213129 49.13313808]%


values can be specified manually as well. 

In [18]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [19]:
list_1 = np.array([4,5,12,36])
list_2 = np.array([86,778,12,45])
print(f"values of list_1 : {list_1}")
print(f"values of list_2 : {list_2}")
sum_of_list_1_to_list_2 = list_2 + list_1

print(f"sum of two list {sum_of_list_1_to_list_2}")


values of list_1 : [ 4  5 12 36]
values of list_2 : [ 86 778  12  45]
sum of two list [ 90 783  24  81]


# 3.4 Operations on Vectors 

Let's explore some operations using vectors 


# 3.4.1 Indexing

Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference Slicing and Indexing for more details.
Indexing means referring to an element of an array by its position within the array.
Slicing means getting a subset of elements from an array based on their indices.
NumPy starts indexing at zero so the 3rd element of an vector  𝐚
  is a[2].

In [28]:
a = np.arange(10)
b = a[2]
print(f"{a[2].shape} a[2]= {b}")
try:
    c=a[10]
except Exception as e :
    print("the error message you'll see is :")
    print(e)

() a[2]= 2
the error message you'll see is :
index 10 is out of bounds for axis 0 with size 10


## 3.4.2 Slicing

Slicing creates an array of indices using a set of three values (start:stop:step). A subset of values is also valid. Its use is best explained by example

In [33]:
# vector slicing operator 

a = np.arange(10)
print(f"a      = {a}") 

# access 3 elements separated by two : 
c = a[2:7:2] ; print("a[2:7:2]",c)
# access all elements below index 3 

c=a[3:]; print("a[3:] = ",c )
# access all elements 

all_elements = a[:] ; print("all elements of a :  ",all_elements )

a      = [0 1 2 3 4 5 6 7 8 9]
a[2:7:2] [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
all elements of a :   [0 1 2 3 4 5 6 7 8 9]


# 3.4.3 Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [39]:
a = np.array([1,2,3,5,8,63])

# negate elements of a 

negatif_of_a = -a 

print(f"negatif elements of a : {negatif_of_a}")

# sum all elements of a , returns a scalar 

sum_of_a = np.sum(a)
print(f"somme of all elements of a : {sum_of_a}")

# let's calculate the mean of a 

mean_of_a = int(np.mean(a))
print("mean of elements a is : ", mean_of_a)

# let's elevate a in square 

a_carré = a**2 

print("tous les elements de a elevés au carré est : ", a_carré)

negatif elements of a : [ -1  -2  -3  -5  -8 -63]
somme of all elements of a : 82
mean of elements a is :  13
tous les elements de a elevés au carré est :  [   1    4    9   25   64 3969]


### 3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [43]:
vector_1 = np.array([1,85,23,89])
vector_2 = np.array([74,85,23,45])

# addition 
print(f"sum of vector1 + vector2 = ", (vector_1 +vector_2))
# substraction 
print(f"substraction  of vector1 and vector2 = ", (vector_1 - vector_2))
# division 
print(f"division of vector1 / vector2 = ", (vector_1  / vector_2))
# multiplication  

print(f"multiplication of vector1 and  vector2 = ", (vector_1  * vector_2))


# Remark the vector must be the same size 

c = np.array([1,56])
try :
    d = a +c 
except Exception as e : 
    print("The error message you'll see is :")
    print(e)

sum of vector1 + vector2 =  [ 75 170  46 134]
substraction  of vector1 and vector2 =  [-73   0   0  44]
division of vector1 / vector2 =  [0.01351351 1.         1.         1.97777778]
multiplication of vector1 and  vector2 =  [  74 7225  529 4005]
The error message you'll see is :
operands could not be broadcast together with shapes (6,) (2,) 


### 3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [44]:
# le produit scalaire sur les vecteurs 

scalar_number = 100

a = np.array([1,8,3,6])

# multiply a by a scalar 

b = a*scalar_number 

print("la valeur du produit scalaire du vecteur a est : ", b)



la valeur du produit scalaire du vecteur a est :  [100 800 300 600]


# 3.4.6 Vector Vector dot product

The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below

In [45]:
# le produit scalaire vectoriel multiplie les elements de deux vecteurs et les additionne entre eux . 

def my_dot(a, b):
    """
    Compute the dot product of two vectors 

    Arg :

    a : input vector 
    b : second input vector , all with the same size 
    
    """

    x = 0
    for i in range(a.shape[0]):
        x = x + a[i]*b[i]
    return x 

In [46]:
# test 1-D 

a = np.array([1,2,3,4])
b = np.array([-1,89,45,23])
print(f"my_dot(a,b) = {my_dot(a,b)}")

my_dot(a,b) = 404


In [47]:
c = a *b 
print(c)
g = sum(c)
print(g)

[ -1 178 135  92]
404


### 3.4.7 The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [56]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)


tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(f"np.dot(a,b )= {c:4f}")
print(f"Vectorized version duration : {1000 * (toc - tic ):.4f} ms")

tic = time.time()
c = my_dot(a,b )
toc = time.time()

print(f"my_dot(a, b)= {c:4f}")
print(f"loop version duration : {1000 * (toc -tic ):.4f} ms")
del(a); del(b)

np.dot(a,b )= 2501072.581681
Vectorized version duration : 32.3596 ms
my_dot(a, b)= 2501072.581681
loop version duration : 3299.5703 ms


In [57]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


# Matrices 

## 4.1 Abstract

Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1. 

In [58]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [62]:
M = np.array([[1,5,8],[7,8,9]])
print(M.shape)


# Transposition 
print("la transposition de la matrice M donne comme resultat celui-ci : ", M.T)

(2, 3)
la transposition de la matrice M donne comme resultat celui-ci :  [[1 7]
 [5 8]
 [8 9]]


In [63]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


## 4.4 Operations on Matrices
Let's explore some operations using matrices.

### 4.4.1 Indexing

Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below


In [64]:
a = np.arange(6).reshape(-1,2)
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]


In [65]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


In [68]:
M = np.array([
[1,2,5], 
[8,45,78], 

[10,78,56]

])
print(M)

[[ 1  2  5]
 [ 8 45 78]
 [10 78 56]]


In [71]:
sub_matrix = M[0:3, 0:2]
print(sub_matrix)

[[ 1  2]
 [ 8 45]
 [10 78]]


In [73]:
# acceder a une ligne specifique 

second_row = M[1,:]
print(second_row)

[ 8 45 78]


In [74]:
# acceder a une colonne specifique 


third_column = M[:,2]
print("les elements de la 3eme colonne ", third_column)

les elements de la 3eme colonne  [ 5 78 56]


In [75]:
# Acceder a un element spécifique 

element = M[1, 2]
print("affiche l'elemnent ", element)

affiche l'elemnent  78


In [77]:
step_matrix = M[::2, ::2]
print(step_matrix)
print(M)

[[ 1  5]
 [10 56]]
[[ 1  2  5]
 [ 8 45 78]
 [10 78 56]]


In [78]:
a = np.arange(10)
b = a[::2]
print(b)

[0 2 4 6 8]
